name: DevOps Lab Exercise
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  # Trigger the workflow on push or pull request events for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies (npm ci is faster if using package-lock.json)
    #  - run: npm ci

      # Build the project (if build script exists)
      - run: npm run build --if-present

      # Run tests
      - run: npm test
